services:
  - docker

before_install:
  - docker build -t shayoo/dotnettest .

script:
  - echo "run tests here"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shayoo/dotnettest

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: dotnettest3
  env: Dotnettest3-env
  bucket: elasticbeanstalk-eu-west-1-322845887271
  bucket_path: dotnettest3
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
