language: csharp
mono: none
dotnet: 5.0.102

services:
  - docker

before_install:
  - docker build -t shayoo/dotnettest .

script:
  - dotnet restore

after_success:
  - echo "$DOCKER_PASSWORD" | docker login - "$DOCKER_ID" --password-stdin
  - docker push shayoo/dotnettest
